[package]
name = "rodrick160/uservaultservice"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
private = false

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
Trove = "sleitnick/trove@1.1.0"

[server-dependencies]
ProfileService = "tazmondo/profileservice@1.0.6"