[package]
name = "rodrick160/uservault"
version = "0.2.13"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = false

[dependencies]
Comm = "sleitnick/comm@1.0.1"
Fusion2 = "elttob/fusion@0.2.0"
Fusion3 = "fizzyhex/fusion-beta@0.3.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
Trove = "sleitnick/trove@1.1.0"

[server-dependencies]
ProfileService = "tazmondo/profileservice@1.0.6"